const fs = require('fs');
const path = 'src/data/lessons.json';
const data = JSON.parse(fs.readFileSync(path));

const science = {
  'sci_food_1': { 'what': 'Our food contains nutrients like carbohydrates, proteins, fats, vitamins, and minerals that give us energy and keep us healthy.', 'example': 'Eating rice gives you energy (carbs), while dal helps you grow (proteins).', 'points': ['Carbohydrates and fats are energy-giving foods', 'Proteins are body-building foods needed for growth', 'Roughage helps in digestion but is not a nutrient'], 'tip': 'Wash vegetables before cutting them to keep the vitamins safe!', 'question': 'Which nutrient is known as the body-building food?' },
  'sci_food_2': { 'what': 'A balanced diet provides all nutrients in right amounts. Lack of these leads to deficiency diseases.', 'example': 'Lack of Vitamin C causes scurvy where gums bleed.', 'points': ['Vitamin A deficiency causes night blindness', 'Vitamin D deficiency (and lack of sunlight) causes rickets', 'Iodine deficiency causes goiter (swelled neck)'], 'tip': 'A rainbow-colored plate (different veggies) usually means a balanced meal!', 'question': 'What disease is caused by the deficiency of Iron?' },
  'sci_plt_1': { 'what': 'Plants are grouped into herbs (soft stems), shrubs (woody stems at base), and trees (hard, thick trunks).', 'example': 'Tulsi is a herb, Rose is a shrub, and Mango is a tree.', 'points': ['Herbs are usually short and live for one season', 'Shrubs have branches near the ground', 'Trees have branches high up on the stem'], 'tip': 'Climbers and creepers are special plants that need support to grow up!', 'question': 'Is a Peepal tree a herb, shrub, or tree?' },
  'sci_plt_2': { 'what': 'Each part of a plant — root, stem, leaf, flower — has a vital job to do.', 'example': 'The leaf is like a kitchen where the plant\'s food is cooked.', 'points': ['Roots absorb water and anchor the plant', 'Stem carries water and food to all parts', 'Flowers are the reproductive parts that become seeds'], 'tip': 'Most plants have two types of roots: Taproot or Fibrous root!', 'question': 'What is the flat green part of a leaf called?' },
  'sci_plt_3': { 'what': 'The process by which green plants make their own food using sunlight, air (CO2), and water.', 'example': 'Plants take in carbon dioxide and give us fresh oxygen to breathe!', 'points': ['Chlorophyll is the green pigment that traps sunlight', 'Stomata are tiny pores on leaves for gas exchange', 'Glucose is the food produced, stored as starch'], 'tip': 'Photosynthesis happens mostly during the day when sunlight is available.', 'question': 'Which gas do plants release during photosynthesis?' },
  'sci_body_1': { 'what': 'Our body has different joints like ball-and-socket, hinge, and pivot that allow us to move in different ways.', 'example': 'Your elbow works like a door hinge — it only moves back and forth.', 'points': ['Ball-and-socket joints (shoulder) allow movement in all directions', 'Fixed joints (skull) don\'t allow any movement', 'The backbone is made of many small bones called vertebrae'], 'tip': 'Regular exercise keeps your joints flexible and healthy!', 'question': 'Where in your body can you find a ball-and-socket joint?' },
  'sci_body_2': { 'what': 'Our skeleton provides shape and protection, while muscles help the bones move.', 'example': 'Touch your arm and feel the muscles bulge when you lift something heavy.', 'points': ['The rib cage protects our heart and lungs', 'Muscles can only pull, they cannot push', 'Cartilage is a softer tissue found at joints and in your nose/ears'], 'tip': 'Bones need Calcium and Vitamin D to stay strong!', 'question': 'How many bones are there in the human adult skeleton?' },
  'sci_liv_1': { 'what': 'A habitat is the natural home of an organism, providing food, water, and shelter.', 'example': 'A pond is a habitat for fish; a forest is a habitat for tigers.', 'points': ['Terrestrial habitats include deserts, mountains, and grasslands', 'Aquatic habitats include oceans, rivers, and lakes', 'The place where an organism lives is its address in nature'], 'tip': 'Different habitats have different weather and plants!', 'question': 'Is an ocean a terrestrial or aquatic habitat?' },
  'sci_liv_2': { 'what': 'Adaptation is the presence of specific features that help a plant or animal survive in its surroundings.', 'example': 'Fish have gills to breathe underwater; camels have thick skin for the desert sun.', 'points': ['Desert plants have spines instead of leaves to save water', 'Mountain animals have thick fur to stay warm', 'Aquatic plants have hollow stems to stay afloat'], 'tip': 'Adaptations happen over thousands of years to help species survive!', 'question': 'How do gills help a fish?' },
  'sci_mat_1': { 'what': 'Grouping materials based on properties like appearance, hardness, and whether they sink or float.', 'example': 'Steel is hard and shiny; wood is rough and floats in water.', 'points': ['Lustrous materials have a natural shine (like gold)', 'Soluble substances dissolve in water (like sugar)', 'Transparent materials let light pass through (like glass)'], 'tip': 'Sorting things helps us find them easily and understand their uses!', 'question': 'Name one material that is transparent.' },
  'sci_sep_1': { 'what': 'Methods like handpicking, winnowing, and sieving used to separate components of a mixture.', 'example': 'Your mother picks out small stones from rice — that\'s handpicking.', 'points': ['Winnowing uses wind to separate heavy grains from light husks', 'Sieving uses a mesh to separate particles of different sizes', 'Sedimentation is letting heavy dirt settle in water'], 'tip': 'Use filtration with a cloth or paper to remove very fine dirt from water!', 'question': 'Why do we use winnowing for separating grains?' },
  'sci_sep_2': { 'what': 'Evaporation is water turning into vapor; condensation is vapor turning back into liquid.', 'example': 'Steam from a boiling kettle disappears (evaporation).', 'points': ['Salt is obtained from sea water by evaporation', 'The water cycle depends on these two processes', 'Distillation uses both to get very pure water'], 'tip': 'The "sweat" on the outside of a cold soda can is condensation!', 'question': 'How is salt made from sea water?' },
  'sci_chg_1': { 'what': 'Reversible changes can be undone (like melting ice); irreversible changes are permanent (like burning wood).', 'example': 'Inflation of a balloon is reversible; bursting it is irreversible.', 'points': ['Folding paper is reversible', 'Cooking food is an irreversible change', 'Curdling of milk into curd is irreversible'], 'tip': 'Most physical changes are reversible, while most chemical changes are not.', 'question': 'Is the melting of wax a reversible or irreversible change?' },
  'sci_mot_1': { 'what': 'Measurement is comparing an unknown quantity with a known fixed quantity called a unit.', 'example': 'Measuring the length of your desk using a 15-cm ruler.', 'points': ['SI unit of length is the Metre (m)', 'Ancient people used hand-span or cubit, which were not accurate', '1 kilometer = 1000 meters'], 'tip': 'Always keep the ruler exactly along the length you are measuring!', 'question': 'What is the standard unit of length across the world?' },
  'sci_mot_2': { 'what': 'Motion is the change in position of an object over time. It can be straight, circular, or periodic.', 'example': 'A car moving on a straight road (rectilinear); a fan (circular).', 'points': ['Rectilinear motion is in a straight line', 'Periodic motion repeats after equal intervals (like a pendulum)', 'Circular motion happens when an object moves around a center point'], 'tip': 'A rolling ball has both rectilinear and rotational motion!', 'question': 'What type of motion does a swinging cradle have?' },
  'sci_lgt_1': { 'what': 'Light is a form of energy that helps us see. Shadows form when an object blocks light.', 'example': 'A puppet show uses shadows cast on a screen.', 'points': ['Sources can be luminous (Sun) or non-luminous (Moon)', 'Opaque objects block light completely and form dark shadows', 'Transparent objects let all light pass through'], 'tip': 'Light always travels in a straight line!', 'question': 'Can a transparent object form a dark shadow?' },
  'sci_lgt_2': { 'what': 'Reflection is the bouncing back of light from a surface, like a mirror.', 'example': 'Looking at your face in a mirror.', 'points': ['A mirror changes the direction of light falling on it', 'A pinhole camera forms an inverted (upside down) image', 'Smooth surfaces reflect light better than rough ones'], 'tip': 'Periscopes use reflection to see over or around obstacles.', 'question': 'What kind of image is formed by a pinhole camera?' },
  'sci_elec_1': { 'what': 'An electric circuit is a path through which current flows from a cell to a device.', 'example': 'A torch works when the circuit is completed by the switch.', 'points': ['An electric cell has a positive (+) and negative (-) terminal', 'A closed circuit allows current; an open circuit stops it', 'The filament of a bulb is the thin wire that glows'], 'tip': 'Always use a switch to safely turn devices on and off!', 'question': 'How many terminals does an electric cell have?' },
  'sci_elec_2': { 'what': 'Conductors allow electricity to pass through; insulators do not.', 'example': 'Metals are good conductors; plastic and rubber are insulators.', 'points': ['Copper is used in wires because it is a great conductor', 'Plastic coating on wires protects us from electric shocks', 'Water (unless very pure) is also a conductor'], 'tip': 'Never touch electric switches with wet hands!', 'question': 'Is wood a conductor or an insulator?' },
  'sci_mag_1': { 'what': 'Magnets are materials that attract iron. They always have two poles: North and South.', 'example': 'A magnetic compass helps sailors find their way at sea.', 'points': ['Like poles repel; unlike poles attract each other', 'A freely suspended magnet always points North-South', 'Magnetic property is strongest at the poles'], 'tip': 'Never heat or drop a magnet, or it might lose its power!', 'question': 'What happens when two North poles are brought close to each other?' },
  'sci_wtr_1': { 'what': 'Water is essential for life. We get it from rivers, lakes, ponds, and groundwater.', 'example': 'Drinking, bathing, and watering plants are daily uses of water.', 'points': ['Only a very small part of Earth\'s water is usable fresh water', 'Groundwater is pulled out using wells and hand-pumps', 'Plants need water to survive and stay cool'], 'tip': 'Save water by turning off the tap while brushing your teeth!', 'question': 'What is the main source of water on Earth?' },
  'sci_wtr_2': { 'what': 'The continuous movement of water from Earth to the atmosphere and back.', 'example': 'Rain falling on a hot road and disappearing into the air.', 'points': ['Clouds are formed by the condensation of water vapor', 'Precipitation is when water falls back as rain, snow, or hail', 'Transpiration is the release of water vapor by plant leaves'], 'tip': 'The sun is the engine that drives the whole water cycle!', 'question': 'What is the process of plants releasing water into the air called?' },
  'sci_air_1': { 'what': 'Air is a mixture of gases that surrounds the Earth like a blanket called the atmosphere.', 'example': 'Blowing into a balloon shows that air occupies space.', 'points': ['Nitrogen makes up nearly 78% of the air', 'Oxygen is essential for breathing and burning', 'Air contains dust, smoke, and water vapor too'], 'tip': 'Even soil and water have some air trapped in them!', 'question': 'Which gas in the air is needed for things to burn?' },
  'sci_grb_1': { 'what': 'Waste management is about reducing garbage and using methods like composting and recycling.', 'example': 'Turning kitchen waste like fruit peels into manure (compost).', 'points': ['Green bins are for biodegradable waste (food)', 'Blue bins are for non-biodegradable waste (plastic, glass)', 'Vermicomposting uses redworms to make high-quality manure'], 'tip': 'Follow the 3 Rs: Reduce, Reuse, and Recycle!', 'question': 'What are redworms used for in waste management?' }
};

Object.assign(data, science);
fs.writeFileSync(path, JSON.stringify(data, null, 2));
console.log('Science topics updated.');
