const fs = require('fs');
const path = 'src/data/lessons.json';
const data = JSON.parse(fs.readFileSync(path));

const ss = {
  'ss_his_1': { 'what': 'History is the study of our past. We learn about it from sources like manuscripts, inscriptions, and archeological findings.', 'example': 'Finding an old coin from your grandfather\'s time is a piece of your personal history.', 'points': ['Manuscripts were hand-written on palm leaves', 'Inscriptions were carved on hard surfaces like stone', 'History helps us understand how our ancestors lived'], 'tip': 'BC/BCE means Before Common Era; AD/CE means Common Era.', 'question': 'Where were manuscripts usually written in ancient India?' },
  'ss_his_2': { 'what': 'Early humans were hunter-gatherers who later learned to farm and live in one place.', 'example': 'Early humans lived in caves like Bhimbetka to protect themselves from weather.', 'points': ['The discovery of fire changed human life forever', 'Humans started taming animals and growing crops like wheat', 'The wheel was a major invention of this period'], 'tip': 'The Paleolithic age is also known as the Old Stone Age.', 'question': 'Why did early humans live in caves?' },
  'ss_his_3': { 'what': 'The Indus Valley Civilization (or Harappan) was one of the world\'s earliest urban cultures with planned cities.', 'example': 'The Great Bath of Mohenjodaro is an example of advanced engineering.', 'points': ['Cities had a citadel and a lower town', 'They used baked bricks for building houses', 'They had an amazing drainage system that was covered'], 'tip': 'Harappan cities were famous for their grid-like street patterns!', 'question': 'Which civilization is known for its "Great Bath"?' },
  'ss_his_4': { 'what': 'The Vedic period is known for the Vedas, especially the Rigveda, and the megalithic burial sites.', 'example': 'The Rigveda contains hymns called "Suktas" spoken in praise of various deities.', 'points': ['There are four Vedas: Rigveda, Samaveda, Yajurveda, Atharvaveda', 'Megaliths are large stone structures used as burial markers', 'Chariots were drawn by horses and used in battles'], 'tip': 'Iron tools were a major technological leap during the later Vedic period!', 'question': 'Which is the oldest Veda?' },
  'ss_his_5': { 'what': 'Rise of Mahajanapadas (large kingdoms) like Magadha and republics like Vajji.', 'example': 'Magadha became powerful because it was surrounded by rivers and iron ore mines.', 'points': ['Rajas realized the importance of taxes to maintain armies', 'Fortifications (walls) were built around major cities', 'Magadha had two very powerful rulers: Bimbisara and Ajatashatru'], 'tip': 'Vajji was a Gana or Sangha, which means it was ruled by a group of people!', 'question': 'What was the capital of Magadha?' },
  'ss_his_6': { 'what': 'Rise of new religious ideas by Siddhartha (Buddha) and Mahavira, and the philosophy of Upanishads.', 'example': 'The story of Kisagotami teaches us about the inevitability of death.', 'points': ['Buddhism teaches the Eightfold Path to end suffering', 'Jainism emphasizes Ahimsa (non-violence) for all living beings', 'The Upanishads discuss the nature of the soul (Atman) and Brahman'], 'tip': 'Buddhacharita is a famous biography of the Buddha!', 'question': 'What was the original name of the Buddha?' },
  'ss_his_7': { 'what': 'Ashoka was a unique Mauryan ruler who gave up war after the Kalinga battle and spread Dhamma.', 'example': 'Ashoka\'s messages are still found on pillars across India.', 'points': ['Ashoka used Prakrit language so common people could understand', 'He appointed Dhamma Mahamattas to teach people ethical living', 'The lion capital on our currency is from Ashoka\'s pillar at Sarnath'], 'tip': 'Ashoka was the first king in world history to give up conquest after winning a war.', 'question': 'Which battle changed Ashoka\'s life?' },
  'ss_his_8': { 'what': 'Growth of towns and trade led to prosperous villages and the rise of the Silk Route.', 'example': 'Ancient Indian spices and silk were very famous in the Roman Empire.', 'points': ['Guilds (shrenis) were groups of artisans and merchants', 'Iron tools like the ploughshare increased agricultural yield', 'South India was famous for gold, spices, and precious stones'], 'tip': 'The Silk Route was a network of trade routes connecting China to the West!', 'question': 'What was a "Shreni" in ancient India?' },
  'ss_his_9': { 'what': 'After the Mauryas, new dynasties like the Guptas and Pallavas established powerful kingdoms.', 'example': 'The Prayag Prashasti tells us about the great conquests of Samudragupta.', 'points': ['Harshavardhana was a famous king of Thanesar', 'The Guptas were known for great developments in science and art', 'The Pallavas and Chalukyas were major powers in South India'], 'tip': 'Prashasti means "in praise of" in Sanskrit!', 'question': 'Who was the court poet of Samudragupta?' },
  'ss_his_10': { 'what': 'Ancient India was a hub of great architecture (temples, stupas) and literature.', 'example': 'The Sanchi Stupa is a world-famous Buddhist monument.', 'points': ['Kalidasa wrote the famous play Abhijnanashakuntalam', 'Aryabhata was a great mathematician and astronomer', 'Puranas and Epics like Ramayana and Mahabharata were compiled'], 'tip': 'The Iron Pillar at Mehrauli has not rusted even after 1500 years!', 'question': 'Who wrote the book "Aryabhatiyam"?' },
  'ss_geo_1': { 'what': 'The Earth is one of the eight planets in the solar system, orbiting the Sun.', 'example': 'Looking at the North Star (Pole Star) helps travelers find direction at night.', 'points': ['The Sun is at the center of the solar system', 'The Milky Way is the galaxy which includes our solar system', 'Earth is the only planet known to support life'], 'tip': 'Mercury is the closest planet to the sun, but Venus is the hottest!', 'question': 'Which is the largest planet in our solar system?' },
  'ss_geo_2': { 'what': 'Latitudes and longitudes are imaginary lines on the globe used to locate any place.', 'example': 'The Equator is the 0° latitude that divides Earth into two halves.', 'points': ['The Prime Meridian (0° longitude) passes through Greenwich', 'The area between the Tropics is the hottest zone (Torrid Zone)', 'Standard Time in India is based on the 82°30\' E longitude'], 'tip': 'Latitudes are like rungs on a ladder; Longitudes go from pole to pole!', 'question': 'What is the latitude of the North Pole?' },
  'ss_geo_3': { 'what': 'The Earth has two motions: Rotation (spinning on axis) and Revolution (moving around the sun).', 'example': 'Rotation causes day and night; Revolution causes seasons.', 'points': ['Earth takes 24 hours for one rotation', 'It takes 365.25 days for one revolution (leap year every 4 years)', 'The tilting of the Earth\'s axis is why we have different seasons'], 'tip': 'A leap year has 366 days, with an extra day in February!', 'question': 'What causes day and night on Earth?' },
  'ss_geo_4': { 'what': 'Maps are flat representations of the Earth or parts of it, including physical, political, and thematic types.', 'example': 'A road map of your city is a thematic map.', 'points': ['Physical maps show natural features like mountains and rivers', 'Political maps show boundaries of countries and states', 'Symbols and colors represent different things on a map'], 'tip': 'The top of a map is almost always North!', 'question': 'What type of map shows rainfall or industries?' },
  'ss_geo_5': { 'what': 'The four major spheres of Earth: Lithosphere (land), Hydrosphere (water), Atmosphere (air), and Biosphere (life).', 'example': 'The Biosphere is the narrow zone where land, water, and air interact to support life.', 'points': ['Asia is the largest continent on Earth', 'The Pacific is the largest and deepest ocean', 'Nitrogen and Oxygen are the main gases in the atmosphere'], 'tip': 'Mount Everest is the highest point on the Lithosphere!', 'question': 'Which is the largest continent on Earth?' },
  'ss_geo_6': { 'what': 'Major landforms include mountains, plateaus, and plains formed by internal and external processes.', 'example': 'The Himalayas are young fold mountains.', 'points': ['Plateaus are flat-topped tablelands like the Deccan Plateau', 'Plains are fertile lowlands formed by river deposits', 'Block mountains form when large areas are broken and displaced'], 'tip': 'Most of the world\'s population lives in plains because they are easy to farm!', 'question': 'Name a plateau in India.' },
  'ss_geo_7': { 'what': 'India is a vast country with diverse physical features like the Himalayas, the Thar Desert, and the Coastal Plains.', 'example': 'India is surrounded by the Arabian Sea, Bay of Bengal, and the Indian Ocean.', 'points': ['The Tropic of Cancer passes almost through the middle of India', 'India has 28 states and 8 union territories', 'The Himalayas mean the "Abode of Snow"'], 'tip': 'India is the 7th largest country in the world by area!', 'question': 'Which ocean is named after India?' },
  'ss_geo_8': { 'what': 'Exploring India\'s tropical monsoon climate, diverse forests, and rich wildlife.', 'example': 'The Gir forest in Gujarat is the only home of the Asiatic lion.', 'points': ['Monsoon rains are vital for Indian agriculture', 'Evergreen forests stay green all year round', 'Wildlife sanctuaries protect endangered animals'], 'tip': 'Trees like Neem and Tulsi have great medicinal value!', 'question': 'What type of climate does India have?' },
  'ss_civ_1': { 'what': 'Diversity means variety — in language, religion, food, and culture. India is a land of great diversity.', 'example': 'In your class, friends might speak different languages at home but study together.', 'points': ['Unity in Diversity is a phrase coined by Jawaharlal Nehru', 'Historical and geographical factors influence diversity', 'Diversity enriches our lives by exposing us to new perspectives'], 'tip': 'Despite our differences, we are all part of one big family — India!', 'question': 'Who coined the phrase "Unity in Diversity"?' },
  'ss_civ_2': { 'what': 'Prejudice and stereotypes lead to discrimination. Equality is a fundamental right in democracy.', 'example': 'Saying "boys don\'t cry" is a common gender stereotype.', 'points': ['Dr. B.R. Ambedkar fought against the caste system in India', 'The Constitution ensures equality for all citizens', 'Untouchability has been abolished by law'], 'tip': 'Treating everyone with respect is the first step toward equality.', 'question': 'Who is known as the Father of the Indian Constitution?' },
  'ss_civ_3': { 'what': 'Government is a group of people that governs a country or state, making rules and decisions.', 'example': 'The government builds roads and ensures electricity for everyone.', 'points': ['Democracy is rule by the people through representatives', 'Monarchy is rule by a king or queen', 'Government works at three levels: Local, State, and National'], 'tip': 'Universal Adult Franchise means all adults can vote, regardless of their background.', 'question': 'What is the minimum age to vote in India?' },
  'ss_civ_4': { 'what': 'Democracy works through public participation, resolution of conflict, and ensuring equality and justice.', 'example': 'People protest or sign petitions if they don\'t like a government decision.', 'points': ['Regular elections allow people to change the government', 'Conflicts over river water or religion are resolved by law', 'Equality and justice are the pillars of democratic government'], 'tip': 'The police and courts play a huge role in resolving societal conflicts.', 'question': 'How often are general elections held in India?' },
  'ss_civ_5': { 'what': 'The local government in villages, consisting of the Gram Sabha and the Gram Panchayat.', 'example': 'A village Sarpanch leading a meeting to fix the village well.', 'points': ['Gram Sabha is a meeting of all adults in a village', 'Gram Panchayat is the executive body of the village', 'Panchayati Raj has three levels: Village, Block, and District'], 'tip': 'Gram Sabha is the best example of direct democracy at the root level!', 'question': 'Who is the head of the Gram Panchayat?' },
  'ss_civ_6': { 'what': 'Key officials like the Patwari and the SHO ensure peace and record-keeping in rural areas.', 'example': 'The Patwari measuring land to resolve a boundary dispute between farmers.', 'points': ['Patwari maintains land records and collects revenue', 'SHO (Station House Officer) is the head of the local police station', 'District Collector is the head of the entire district administration'], 'tip': 'The Hindu Succession Amendment Act (2005) gives equal property rights to daughters.', 'question': 'What is the main job of a Patwari?' },
  'ss_civ_7': { 'what': 'Urban areas are managed by Municipal Corporations (big cities) or Municipal Councils (smaller towns).', 'example': 'Garbage collection trucks and street lights are managed by the municipality.', 'points': ['Ward Councillors are elected representatives for small city wards', 'The Commissioner and administrative staff implement decisions', 'Protests like "The Surat cleaning drive" show community power'], 'tip': 'Elected councillors make the policies; appointed officials carry them out.', 'question': 'What is the head of a Municipal Corporation called?' },
  'ss_civ_8': { 'what': 'Farmers, laborers, and artisans earn their living in villages through agriculture and related work.', 'example': 'Thulasi is a landless laborer who works on other people\'s farms for daily wages.', 'points': ['Small farmers often fall into debt to buy seeds and fertilizers', 'Terrace farming in hilly areas like Nagaland saves water', 'Fishing is a major livelihood in coastal villages'], 'tip': 'Most rural families depend on agriculture, but many also do pottery or weaving.', 'question': 'What is the main problem faced by small farmers?' },
  'ss_civ_9': { 'what': 'In cities, people work in factories, offices, and as street vendors or shopkeepers.', 'example': 'Bachchu Manjhi is a cycle-rickshaw puller who moved from a village to the city for work.', 'points': ['Self-employed people like vendors have no job security', 'Permanent employees get benefits like medical leave and pensions', 'Casual workers are hired only when there is more work'], 'tip': 'Service sector (IT, banking) is growing fast in Indian cities!', 'question': 'Name one benefit of a permanent job compared to a casual job.' }
};

Object.assign(data, ss);
fs.writeFileSync(path, JSON.stringify(data, null, 2));
console.log('Social Science topics updated.');
