const fs = require('fs');
const path = 'src/data/lessons.json';
const data = JSON.parse(fs.readFileSync(path));

const math = {
  'math_pn_1': { 'what': 'Factors are numbers that divide another number exactly. Multiples are the results of multiplying a number.', 'example': 'Factors of 6 are 1, 2, 3, 6 because they all divide 6 without a remainder.', 'points': ['1 is a factor of every number', 'Every number is a multiple of itself', 'Perfect numbers are those where the sum of factors (except itself) equals the number'], 'tip': 'Every number has a finite number of factors but infinite multiples!', 'question': 'What are the factors of 10?' },
  'math_pn_2': { 'what': 'Prime numbers have exactly two factors (1 and itself). Composite numbers have more than two factors.', 'example': '2, 3, 5 are prime; 4, 6, 8 are composite.', 'points': ['2 is the only even prime number', '1 is neither prime nor composite', 'The Sieve of Eratosthenes is a method to find all primes up to a number'], 'tip': 'If a number ends in an even digit, it cannot be prime (except 2)!', 'question': 'What is the smallest composite number?' },
  'math_pn_3': { 'what': 'HCF is the largest factor common to two numbers. LCM is the smallest multiple common to them.', 'example': 'For 4 and 6, HCF is 2 and LCM is 12.', 'points': ['Find HCF using prime factorization or division method', 'LCM is useful for adding fractions with different denominators', 'Product of two numbers = HCF x LCM'], 'tip': 'HCF is always less than or equal to the smallest number; LCM is always more than or equal to the largest!', 'question': 'Find the LCM of 3 and 5.' },
  'math_pn_4': { 'what': 'Quick rules to check if a number can be divided by another without doing the full division.', 'example': 'A number is divisible by 5 if it ends in 0 or 5.', 'points': ['Divisible by 3 if the sum of its digits is divisible by 3', 'Divisible by 6 if it is divisible by both 2 and 3', 'Divisible by 9 if the sum of its digits is divisible by 9'], 'tip': 'Check the sum of digits for 3 and 9; check the last digit for 2, 5, and 10!', 'question': 'Is 123 divisible by 3? Why?' },
  'math_geo_1': { 'what': 'The building blocks of geometry: Points (location), Lines (infinite length), and Angles (space between lines).', 'example': 'The tip of a sharp pencil is a point; a straight road is like a line.', 'points': ['A ray has one starting point and goes on forever', 'A line segment has two fixed end points', 'Angles are measured in degrees using a protractor'], 'tip': 'Parallel lines never meet, no matter how far they go!', 'question': 'How many rays can start from a single point?' },
  'math_geo_2': { 'what': 'Curves are lines that are not necessarily straight. Polygons are closed shapes made only of line segments.', 'example': 'A circle is a closed curve; a triangle is a polygon.', 'points': ['Simple curves do not cross themselves', 'The boundary of a closed shape separates the interior from the exterior', 'A triangle is the polygon with the fewest number of sides'], 'tip': 'A polygon must be "closed" - you cannot have an open polygon!', 'question': 'Is a circle a polygon?' },
  'math_geo_3': { 'what': 'Triangles are 3-sided polygons. Quadrilaterals are 4-sided polygons.', 'example': 'A slice of pizza is roughly a triangle; a book cover is a quadrilateral.', 'points': ['Triangles have 3 vertices, 3 sides, and 3 angles', 'Quadrilaterals include squares, rectangles, and parallelograms', 'The diagonals of a shape connect opposite corners'], 'tip': 'The sum of angles in a triangle is always 180 degrees!', 'question': 'How many sides does a pentagon have?' },
  'math_shp_1': { 'what': 'Using tools like a ruler or divider to find the exact length of line segments.', 'example': 'Measure the length of your pen using a centimeter scale.', 'points': ['A divider helps in comparing lengths more accurately than just a ruler', 'Always look straight down at the ruler to avoid error', 'Lengths are usually measured in mm, cm, or m'], 'tip': 'When using a ruler, start measuring from the 0 mark, not the very edge of the plastic!', 'question': 'Which is more accurate for comparing two lines: a ruler or a divider?' },
  'math_shp_2': { 'what': 'Categorizing angles based on their size: Acute (<90), Obtuse (>90), and Reflex (>180).', 'example': 'The corner of a square is a Right Angle (90 degrees).', 'points': ['Acute angles are "sharp" and smaller than a corner', 'Obtuse angles are "blunt" and larger than a corner', 'A full rotation is exactly 360 degrees'], 'tip': 'A right angle looks like the letter L!', 'question': 'What kind of angle is 120 degrees?' },
  'math_shp_3': { 'what': 'Distinguishing between flat shapes (2D) and solid objects (3D) like cubes and spheres.', 'example': 'A drawing of a ball is 2D; the actual ball you play with is 3D.', 'points': ['2D shapes have length and breadth only', '3D shapes have length, breadth, and height (volume)', 'A cylinder has two circular faces and one curved surface'], 'tip': 'A cube is a special 3D shape where all faces are equal squares!', 'question': 'Give an example of a cone-shaped object in real life.' },
  'math_int_1': { 'what': 'Integers are the set of whole numbers and their negative opposites.', 'example': 'Think of the temperature in cold places like the Arctic (-20 degrees).', 'points': ['Positive integers are to the right of zero', 'Negative integers are to the left of zero', 'Zero is neither positive nor negative'], 'tip': 'The further a negative number is from zero, the smaller it is!', 'question': 'Which is bigger: -5 or -1?' },
  'math_int_2': { 'what': 'Rules for adding and subtracting numbers when some are positive and some are negative.', 'example': 'If you have 5 rupees and owe 3 rupees, you effectively have 5 - 3 = 2 rupees.', 'points': ['Adding a negative number is like subtracting it', 'Subtracting a negative number is like adding its positive version', 'On a number line, + means move right and - means move left'], 'tip': 'Remember: Adding a negative is just going backwards!', 'question': 'What is 5 + (-3)?' },
  'math_frac_1': { 'what': 'A fraction represents a part of a whole, written with a numerator (part) and denominator (whole).', 'example': 'If you eat 1 slice of a 4-slice pizza, you ate 1/4 of the pizza.', 'points': ['The denominator can never be zero', 'Proper fractions are less than 1', 'Representing fractions on a number line helps visualize their value'], 'tip': 'The line between the numbers is called the viniculum or division bar.', 'question': 'What does the denominator in a fraction tell us?' },
  'math_frac_2': { 'what': 'Categorizing fractions based on whether the numerator is smaller or larger than the denominator.', 'example': '1/2 is proper; 3/2 is improper; 1 1/2 is a mixed fraction.', 'points': ['Proper: Numerator < Denominator', 'Improper: Numerator >= Denominator', 'Mixed fractions combine a whole number and a proper fraction'], 'tip': 'You can convert an improper fraction to a mixed fraction by dividing the top by the bottom!', 'question': 'Which type of fraction is 7/4?' },
  'math_frac_3': { 'what': 'Fractions that look different but have the same value when simplified.', 'example': '1/2, 2/4, and 5/10 are all equivalent fractions.', 'points': ['Multiply or divide both numerator and denominator by the same number', 'Simplifying means dividing until they have no common factors except 1', 'Cross-multiplication can check if two fractions are equivalent'], 'tip': 'Equivalent fractions are just different ways of saying the same thing!', 'question': 'Find an equivalent fraction for 3/5.' },
  'math_frac_4': { 'what': 'Finding out which fraction is larger by using a common denominator.', 'example': 'To compare 1/2 and 1/3, turn them into 3/6 and 2/6. 1/2 is larger.', 'points': ['Like fractions (same denominator) are easy to compare', 'For unlike fractions, find the LCM of denominators', 'Cross-multiplication is a fast way to compare two fractions'], 'tip': 'If the numerators are the same, the fraction with the smaller denominator is actually bigger!', 'question': 'Which is larger: 2/5 or 2/7?' },
  'math_frac_5': { 'what': 'Learning to add and subtract parts of a whole.', 'example': '1/4 piece + 1/4 piece = 2/4 = 1/2 of the whole.', 'points': ['For like fractions, just add/subtract the numerators', 'For unlike fractions, change them to like fractions first', 'Always simplify your final answer if possible'], 'tip': 'Think of shared denominator as a shared language between the fractions.', 'question': 'What is 1/2 + 1/4?' },
  'math_dec_1': { 'what': 'Decimals are another way of expressing fractions using a point (.), representing parts of 10, 100, etc.', 'example': '0.5 is the same as 1/2; 0.25 is the same as 1/4.', 'points': ['The first place after the point is Tenths', 'The second place is Hundredths', 'Decimals are used in money (rupees and paise)'], 'tip': 'Zeroes at the end of a decimal (like 0.50) don\'t change its value!', 'question': 'How many tenths make one whole?' },
  'math_dec_2': { 'what': 'Comparing decimal numbers by looking at their place values from left to right.', 'example': '0.5 is bigger than 0.05 because 5 tenths is more than 5 hundredths.', 'points': ['Compare the whole numbers first', 'Then compare tenths, then hundredths', 'Adding zeroes to make lengths equal makes comparison easier'], 'tip': 'Always line up the decimal points when comparing or calculating!', 'question': 'Which is bigger: 1.2 or 1.02?' },
  'math_dec_3': { 'what': 'Performing addition and subtraction with decimal numbers.', 'example': 'Adding 1.5 kg and 2.75 kg of sugar gives 4.25 kg.', 'points': ['Align the decimal points vertically', 'Empty spaces can be filled with zeroes', 'The decimal point goes in the same position in the answer'], 'tip': 'Treat decimals like normal numbers, just don\'t forget to place the dot!', 'question': 'Find the sum of 10.5 and 2.05.' },
  'math_dh_1': { 'what': 'Recording information in an organized way using symbols like tally marks.', 'example': 'Counting the types of birds in a park and using marks to keep track.', 'points': ['A tally mark box (|||| with a slash) represents 5', 'Helps to avoid counting the same item twice', 'Makes large amounts of data easy to read'], 'tip': 'Tallying is the fastest way to record data as it happens!', 'question': 'How do you represent the number 7 using tally marks?' },
  'math_dh_2': { 'what': 'Representing data using pictures (pictographs) or rectangular bars (bar graphs).', 'example': 'A bar graph showing the favorite fruits of students in a class.', 'points': ['Each symbol in a pictograph represents a specific number of items', 'In a bar graph, the height of the bar shows the frequency', 'Graphs give a quick visual summary of the information'], 'tip': 'Always look at the "scale" (e.g., 1 unit = 5 students) specified in the graph.', 'question': 'In a pictograph, if one star represents 10 stars, how many stars do 3 stars represent?' },
  'math_men_1': { 'what': 'Perimeter is the total length of the boundary of a closed figure.', 'example': 'If you walk along the fence of a rectangular garden, you are walking its perimeter.', 'points': ['Perimeter of Square = 4 x side', 'Perimeter of Rectangle = 2 x (length + breadth)', 'Measured in units of length like cm, m, or km'], 'tip': 'Perimeter is "around the edge"; Area is "the space inside".', 'question': 'Find the perimeter of a square with side 5 cm.' },
  'math_men_2': { 'what': 'Area is the amount of surface covered by a closed figure.', 'example': 'The amount of carpet needed to cover a floor is its area.', 'points': ['Area of Square = side x side', 'Area of Rectangle = length x breadth', 'Measured in square units like sq.cm or sq.m'], 'tip': 'Think of area as how many small 1x1 squares can fit inside a shape!', 'question': 'If a rectangle has length 4m and breadth 3m, what is its area?' },
  'math_alg_1': { 'what': 'Algebra uses letters (variables) to represent numbers we don\'t know yet.', 'example': 'If you have x chocolates and get 2 more, you have x + 2 chocolates.', 'points': ['Variables can take different values', 'Constants have a fixed value', 'Helps in writing general rules and formulas'], 'tip': 'In algebra, we often use \'x\' or \'n\' as the most common variables.', 'question': 'Write an expression for \"5 more than y\".' },
  'math_alg_2': { 'what': 'An equation is a statement where two expressions are equal (=).', 'example': 'x + 3 = 10 means what number added to 3 gives 10? (Answer: 7).', 'points': ['The Left Hand Side (LHS) must equal the Right Hand Side (RHS)', 'Solving means finding the value of the variable', 'Maintaining balance is key: do the same to both sides'], 'tip': 'Think of an equation like a balanced weighing scale!', 'question': 'Solve for x: x - 5 = 12.' },
  'math_rp_1': { 'what': 'Ratio is a way of comparing two quantities of the same kind by division.', 'example': 'If there are 2 boys and 3 girls, the ratio of boys to girls is 2:3.', 'points': ['The symbol for ratio is \':\'', 'Ratios have no units', 'Always write ratios in their simplest form'], 'tip': 'The order of numbers in a ratio matters! 2:3 is not the same as 3:2.', 'question': 'In a class of 20 boys and 30 girls, what is the ratio of boys to girls?' },
  'math_rp_2': { 'what': 'Proportion means that two ratios are equal.', 'example': 'If 2:3 = 4:6, then 2, 3, 4, 6 are in proportion.', 'points': ['The symbol for proportion is \'::\'', 'Extremes (first and last) and Means (middle two) numbers', 'Product of extremes = Product of means'], 'tip': 'Proportion is just a way of saying "the relationship is the same".', 'question': 'Are 2, 4, 8, 16 in proportion?' },
  'math_rp_3': { 'what': 'A method where we find the value of one unit first and then find the value of the required number of units.', 'example': 'If 5 pens cost 50, first find 1 pen (10), then find 10 pens (100).', 'points': ['Value of one = Total value / Number of units', 'More units = Value of one x Required number of units', 'Very useful for shopping and daily calculations'], 'tip': "Always go 'down to one' before going 'up to many'!", 'question': 'If 3 notebooks cost 90, how much will 5 cost?' },
  'math_sym_1': { 'what': 'A line that divides a shape into two identical halves that match exactly.', 'example': 'If you fold a paper heart in half, the fold is the line of symmetry.', 'points': ['Some shapes have one, many, or no lines of symmetry', 'A circle has infinite lines of symmetry', 'A square has four lines of symmetry'], 'tip': 'Think of a line of symmetry like a mirror line.', 'question': 'How many lines of symmetry does a rectangle have?' },
  'math_sym_2': { 'what': 'The type of symmetry where one half is the mirror image of the other.', 'example': 'Your reflection in a mirror shows reflection symmetry.', 'points': ['The object and its image are at equal distance from the mirror line', 'Left and right are often reversed in reflection', 'Nature uses reflection symmetry in wings of butterflies'], 'tip': 'Check for reflection by holding a small mirror along the symmetry line.', 'question': 'Which letter of the alphabet has vertical reflection symmetry? (A, B, or C?)' },
  'math_pg_1': { 'what': 'Learning to use a compass to draw perfect circles and arcs of a given radius.', 'example': 'Spinning a compass to make a perfectly round ring.', 'points': ['The fixed point is the center of the circle', 'The distance from center to boundary is the radius', 'An arc is just a part of a circle'], 'tip': 'Keep your compass needle firm and your pencil sharp for best results!', 'question': 'What is the line segment joining any two points on a circle called?' },
  'math_pg_2': { 'what': 'Constructing lines of exact length and dividing them exactly into two halves.', 'example': 'Using a compass to find the exact middle of a line segment.', 'points': ['Bisect means to cut into two equal parts', 'A perpendicular bisector meets the line at 90 degrees', 'Constructing using only a ruler and compass is a classic skill'], 'tip': 'Arcs are your best friends in construction — they help find exact points!', 'question': 'What angle does a perpendicular bisector make with the line?' },
  'math_pg_3': { 'what': 'Using a protractor or compass to draw angles like 60, 90, and 120 degrees.', 'example': 'Creating a perfect 90-degree corner for a drawing of a house.', 'points': ['A protractor is used for any specified angle', 'Standard angles can be made using only a compass', 'Bisecting an angle means splitting it into two smaller equal angles'], 'tip': 'Angle construction is all about the steady movement of your hand!', 'question': 'How many degrees is half of a right angle?' }
};

Object.assign(data, math);
fs.writeFileSync(path, JSON.stringify(data, null, 2));
console.log('Math topics updated.');
