const fs = require('fs');
const path = 'src/data/lessons.json';
const data = JSON.parse(fs.readFileSync(path));

const gk = {
  'gk_ca_1': { 'what': 'Staying updated with the latest news about India\'s achievements in sports, space, and science.', 'example': 'Knowing about the latest ISRO mission or a gold medal won at the Olympics.', 'points': ['India has made great progress in digital technology (UPI)', 'The Khelo India program encourages young sports stars', 'ISRO is one of the top space agencies in the world'], 'tip': 'Reading a newspaper for 10 minutes daily is a great habit!', 'question': 'Which space agency of India recently sent missions to the Moon?' },
  'gk_ca_2': { 'what': 'Understanding how the world works together through organizations like the UN and WHO.', 'example': 'The World Health Organization (WHO) helped countries during the pandemic.', 'points': ['The UN (United Nations) works for world peace', 'Climate change is a global issue that all countries are fighting together', 'Sustainable Development Goals aim to end poverty by 2030'], 'tip': 'Knowledge of international events helps you become a global citizen.', 'question': 'What does WHO stand for?' },
  'gk_ind_1': { 'what': 'Quick facts about our motherland — its states, beautiful symbols, and unique identity.', 'example': 'Did you know the Peacock is our national bird and the Banyan is our national tree?', 'points': ['India has 28 states and 8 union territories', 'The Tiger is our national animal', 'Our national anthem "Jana Gana Mana" was written by Rabindranath Tagore'], 'tip': 'Each state in India has its own unique language and festival!', 'question': 'Which is the national tree of India?' },
  'gk_ind_2': { 'what': 'Fascinating facts about the world\'s continents, oceans, and extreme geographical features.', 'example': 'Mt. Everest is the highest point on Earth, located in the Himalayas.', 'points': ['Asia is the largest continent; Australia is the smallest', 'The Pacific Ocean is so deep that Mt. Everest could fit inside it!', 'The Sahara is the largest hot desert in the world'], 'tip': 'There are seven continents and five major oceans on our planet.', 'question': 'Which is the smallest continent in the world?' },
  'gk_ind_3': { 'what': 'Inspiring stories of people who changed the world through their bravery, science, or art.', 'example': 'Mahatma Gandhi led the struggle for India\'s independence through non-violence.', 'points': ['APJ Abdul Kalam was the "Missile Man of India"', 'Mother Teresa was known for her selfless service to the poor', 'Sachin Tendulkar is one of the greatest cricketers of all time'], 'tip': 'Read biographies of great people to get motivated!', 'question': 'Who is known as the "Missile Man of India"?' },
  'gk_sci_1': { 'what': 'Learning about the inventions that made our lives easier, from the lightbulb to the internet.', 'example': 'Thomas Edison spent years testing thousands of materials to make the first lightbulb.', 'points': ['Alexander Graham Bell invented the telephone', 'The Wright brothers made the first successful flight in an airplane', 'Charles Babbage is credited with the idea of the computer'], 'tip': 'An invention starts with a simple "Why not?" or "What if?"', 'question': 'Who invented the lightbulb?' },
  'gk_sci_2': { 'what': 'Basic understanding of how our amazing body works — our heart, brain, and lungs.', 'example': 'Your heart pumps blood to every part of your body without ever stopping!', 'points': ['The brain is the control center for everything you do', 'Lungs help you take in oxygen and get rid of carbon dioxide', 'Stomach and intestines help turn food into energy'], 'tip': 'Your body is the most complex machine in the world — take good care of it!', 'question': 'Which organ in our body is responsible for thinking?' }
};

Object.assign(data, gk);
fs.writeFileSync(path, JSON.stringify(data, null, 2));
console.log('GK topics updated.');
