const fs = require('fs');
const path = 'src/data/lessons.json';
const data = JSON.parse(fs.readFileSync(path));

const remaining = {
  'eng_gr_1': { 'what': 'Exploring Nouns (names of things/people) and Pronouns (words used instead of names).', 'example': 'Instead of saying "Rahul is good", we say "He is good". "He" is a pronoun.', 'points': ['Nouns can be Common (dog) or Proper (Fido)', 'Collective nouns describe groups (a flock of birds)', 'Pronouns like I, you, we, they make sentences smoother'], 'tip': 'Proper nouns always start with a capital letter!', 'question': 'Can you find three nouns and two pronouns in your room?' },
  'eng_gr_2': { 'what': 'Verbs are action words that tell us what someone or something is doing.', 'example': 'Run, jump, study, and even "is" are all verbs.', 'points': ['Main verbs show the primary action', 'Helping verbs like "am, is, are" support the main verb', 'Every complete sentence must have atleast one verb'], 'tip': 'Verbs are the engine of a sentence — they keep it moving!', 'question': 'What is the verb in the sentence: "Sadiya is reading a book"?' },
  'eng_gr_3': { 'what': 'Adjectives describe Nouns, while Adverbs describe Verbs, Adjectives, or other Adverbs.', 'example': 'A "big" house (adj); He runs "fast" (adv).', 'points': ['Adjectives add color and detail to our descriptions', 'Adverbs often end in "-ly" (slowly, carefully)', 'They help make our writing more interesting and vivid'], 'tip': 'Adverbs answer the question: How, When, or Where?', 'question': 'In "The happy girl sang loudly", which word is the adverb?' },
  'eng_gr_4': { 'what': 'Tenses show when an action happens — in the past, present, or future.', 'example': 'I ate (past), I eat (present), I will eat (future).', 'points': ['Present tense is for things happening now or habits', 'Past tense describes what is already finished', 'Future tense tells us what is going to happen'], 'tip': 'Most past tense verbs end in "-ed", but some are irregular like "ran"!', 'question': 'Change "I walk to school" into the future tense.' },
  'eng_gr_5': { 'what': 'Articles (a, an, the) and Prepositions (in, on, at) are small words with big roles.', 'example': 'The apple is "on" the table.', 'points': ['Use "an" before words starting with vowel sounds (a,e,i,o,u)', 'Prepositions show the position or time of something', '"The" is used for specific things we already know about'], 'tip': "Don't say \"a onion\", say \"an onion\" because 'o' is a vowel!", 'question': 'Which preposition would you use to say where your pencil is?' },
  'eng_gr_6': { 'what': 'A sentence is a group of words that makes complete sense, starting with a capital and ending with a punctuation.', 'example': '"The blue sky" is a phrase. "The sky is blue." is a sentence.', 'points': ['Every sentence has a Subject (who) and a Predicate (what they do)', 'Declarative sentences make statements', 'Interrogative sentences ask questions (?)'], 'tip': 'A sentence is like a train — it needs an engine (verb) to go!', 'question': 'Is "Eating an apple" a complete sentence?' },
  'eng_gr_7': { 'what': 'Active voice means the subject does the action. Passive voice means the action is done to the subject.', 'example': 'Active: Sadiya wrote a story. Passive: A story was written by Sadiya.', 'points': ['Active voice is direct and stronger', 'Passive voice uses the verb "to be" and a past participle', 'Use passive voice when the result is more important than the doer'], 'tip': 'If it was done by someone, start with them for Active voice!', 'question': 'Is "The window was broken" active or passive?' },
  'eng_gr_10': { 'what': 'Story writing is the art of creating a sequence of events with characters, a setting, and a plot.', 'example': 'Every great story starts with a simple "Once upon a time..."', 'points': ['Introduce your characters and where they are', 'Give them a problem to solve (the plot)', 'Show how they solve it and what happens in the end'], 'tip': 'Show, don\'t just tell! Instead of "he was sad", describe his tears.', 'question': 'What are the three main parts of any good story?' },

  'hin_gr_2': { 'what': 'क्रिया किसी काम के होने या करने का बोध कराती है। विशेषण संज्ञा या सर्वनाम की विशेषता बताते हैं।', 'example': 'घोड़ा "तेज़" (विशेषण) "दौड़ता" (क्रिया) है।', 'points': ['क्रिया के बिना वाक्य अधूरा होता है', 'विशेषण शब्द रंग, आकार, गुण आदि बताते हैं', 'जैसे: मोटा, सुंदर, काला, चार'], 'tip': 'विशेषण हमेशा संज्ञा से पहले या बाद में आकर उसकी खूबी बताता है।', 'question': ' "नीला आकाश" में विशेषण शब्द कौन सा है?' },
  'hin_gr_3': { 'what': 'शब्दों के सार्थक समूह को वाक्य कहते हैं। वाक्य के मुख्य दो भाग होते हैं: उद्देश्य और विधेय।', 'example': 'राम (उद्देश्य) किताब पढ़ता है (विधेय)।', 'points': ['वाक्य से मन के भाव स्पष्ट होते हैं', 'सार्थक शब्दों का सही क्रम होना आवश्यक है', 'जैसे: "है रहा पढ़ राम" गलत है, "राम पढ़ रहा है" सही है'], 'tip': 'वाक्य के अंत में पूर्ण विराम (।) लगाना न भूलें!', 'question': 'वाक्य किसे कहते हैं?' },
  'hin_ram_3': { 'what': 'रानी कैकेयी द्वारा राजा दशरथ से दो वरदान माँगने और राम को १४ वर्ष का वनवास मिलने की कहानी।', 'example': 'कैकेयी ने मंथरा की बातों में आकर राम के लिए वनवास माँगा।', 'points': ['पहला वरदान: भरत का राजतिलक', 'दूसरा वरदान: राम को १४ वर्ष का वनवास', 'राजा दशरथ इस निर्णय से बहुत दुखी थे'], 'tip': 'बुरी संगति हमें गलत निर्णय लेने पर मजबूर कर सकती है।', 'question': 'कैकेयी को भड़काने वाली दासी का क्या नाम था?' },
  'hin_ram_4': { 'what': 'राम, सीता और लक्ष्मण का अयोध्या त्यागकर वन की ओर प्रस्थान करने का मार्मिक वर्णन।', 'example': 'पूरी अयोध्या नगरी राम के पीछे वन जाने के लिए तैयार थी।', 'points': ['राम ने प्रसन्नतापूर्वक पिता की आज्ञा का पालन किया', 'सीता और लक्ष्मण ने भी राम के साथ जाने का निश्चय किया', 'केवट ने उन्हें अपनी नाव से गंगा पार कराई'], 'tip': 'पितृ-भक्ति और कर्तव्यपरायणता का उत्तम उदाहरण!', 'question': 'गंगा पार कराते समय राम की मदद किसने की?' },
  
  'comp_prog_3': { 'what': 'Blockly is another visual programming tool that helps you learn the logic of coding by stacking colorful blocks.', 'example': 'Dragging a "Move Forward" block to make a character reach its goal.', 'points': ['It is very similar to Scratch but used in many different apps', 'Helps in understanding how step-by-step instructions (algorithms) work', 'No need to worry about typing errors or syntax!'], 'tip': 'Coding is just a way of talking to a computer in its own language.', 'question': 'Why is visual coding easier for beginners?' },
  'comp_net_2': { 'what': 'Email (Electronic Mail) is a way to send messages and files instantly across the world using the internet.', 'example': 'Sending a greeting card to your cousin in another country via Gmail.', 'points': ['Every user needs a unique Email ID (like student@school.com)', 'The "Subject" line tells what the email is about', 'The "Compose" button is used to start a new email'], 'tip': 'Always check for spelling mistakes before clicking "Send"!', 'question': 'What does "Subject" mean in an email?' }
};

Object.assign(data, remaining);
fs.writeFileSync(path, JSON.stringify(data, null, 2));
console.log('Final remaining topics updated.');
