const fs = require('fs');
const path = 'src/data/lessons.json';
const data = JSON.parse(fs.readFileSync(path));

const ict = {
  'comp_1': { 'what': 'A computer is a smart electronic machine that takes data, processes it, and gives useful output.', 'example': 'Your smartphone is actually a very powerful small computer!', 'points': ['Computer follows Input -> Process -> Output cycle', 'Computers never get tired and are very fast', 'First generation used vacuum tubes; now we use microchips'], 'tip': 'The physical parts of a computer are called Hardware; the programs are Software.', 'question': 'Who is known as the Father of Computing?' },
  'comp_2': { 'what': 'Input devices give data to the computer (keyboard); Output devices show the results (monitor).', 'example': 'A scanner takes a photo and puts it in the computer; a printer takes it out on paper.', 'points': ['Input: Keyboard, Mouse, Scanner, Microphone', 'Output: Monitor, Printer, Speakers, Projector', 'A touchscreen is both an input and an output device'], 'tip': 'The most common keyboard layout is called QWERTY!', 'question': 'Is a printer an input or output device?' },
  'comp_3': { 'what': 'The brain of the computer (CPU) and its storage (RAM/Hard Disk) work together to perform tasks.', 'example': 'Think of the Hard Disk as a big cabinet and RAM as your desktop items you are using right now.', 'points': ['CPU (Central Processing Unit) does all the calculations', 'RAM is temporary memory; Hard Disk is permanent storage', 'The Motherboard connects all parts together'], 'tip': 'More RAM usually makes your computer faster when multi-tasking!', 'question': 'What does CPU stand for?' },
  'comp_os_1': { 'what': 'The Operating System (like Windows) is the main software that manages everything on the computer.', 'example': 'Android is the operating system for many mobile phones.', 'points': ['The Desktop is your main workspace on the screen', 'Icons are small pictures that represent programs', 'The Start Menu helps you find settings and apps'], 'tip': 'You can change your desktop background (wallpaper) to make it look unique!', 'question': 'Name one popular operating system other than Windows.' },
  'comp_os_2': { 'what': 'Files are individual items (like a document or photo); Folders are used to organize files.', 'example': 'Think of a Folder as a drawer and Files as the papers inside it.', 'points': ['Creating a folder helps you group related work together', 'Renaming a file makes it easier to find later', 'Deleting an item puts it in the Recycle Bin (until you empty it)'], 'tip': 'Always give your folders descriptive names like "Science Projects"!', 'question': 'Where do deleted files go on a Windows computer?' },
  'comp_word_1': { 'what': 'MS Word / Google Docs are used to create beautiful documents with different fonts and formats.', 'example': 'You can write a letter to your friend and make the text bold or blue.', 'points': ['B stands for Bold, I for Italic, and U for Underline', 'Alignment can be Left, Center, Right, or Justified', 'Font size makes text bigger or smaller'], 'tip': 'Shortcut: Ctrl + S saves your work instantly!', 'question': 'Which button do you use to make text look slanting?' },
  'comp_word_2': { 'what': 'Adding tables, images, and headers to make your documents professional.', 'example': 'Inserting a colorful photo into your school report.', 'points': ['Tables are used to organize data into rows and columns', 'Headers appear at the top of every page', 'Page Layout helps you set margins and orientation'], 'tip': 'Use "Insert Table" for things like class timetables!', 'question': 'Where are Headers located on a page?' },
  'comp_paint_1': { 'what': 'Using basic tools in MS Paint to draw and fill shapes with colors.', 'example': 'Drawing a house using rectangles and a triangle for the roof.', 'points': ['Pencil tool is for freehand drawing', 'Fill with Color tool (bucket) fills a closed shape', 'Select tool allows you to move parts of your drawing'], 'tip': 'If you make a mistake, use Ctrl + Z to Undo!', 'question': 'Which tool is used to fill a whole shape with a single color?' },
  'comp_prog_1': { 'what': 'Scratch is a visual coding language where you snap blocks together like LEGO to make stories and games.', 'example': 'Making a cat (Sprite) say "Hello!" when you click the green flag.', 'points': ['Sprites are the characters on the screen', 'Backdrops are the backgrounds', 'The Stage is where the action happens'], 'tip': 'Every script in Scratch starts with an Event block (like "When Green Flag Clicked")!', 'question': 'What is the character in Scratch called?' },
  'comp_prog_2': { 'what': 'Loops repeat actions, and Conditions (if-else) help characters make decisions.', 'example': 'Telling a sprite to "repeat 10 times" so it walks across the stage.', 'points': ['A Repeat block saves you from writing the same code again and again', 'If-Else blocks are used for things like: If touching edge, then turn back', 'Sensing blocks help sprites detect things around them'], 'tip': 'Using loops makes your code shorter and smarter.', 'question': 'Which block would you use to repeat an action forever?' },
  'comp_net_1': { 'what': 'The Internet is a global network of computers connected to share information.', 'example': 'Browsing Wikipedia to learn about space is using the internet.', 'points': ['A Web Browser is an app used to view websites', 'A Search Engine (like Google) helps you find specific info', 'WWW stands for World Wide Web'], 'tip': 'Always be careful and ask an adult before visiting new websites!', 'question': 'What is the full form of WWW?' },
  'comp_net_3': { 'what': 'Important rules to stay safe and protect your information while playing or studying online.', 'example': 'Never sharing your home address or password with strangers online.', 'points': ['Use strong passwords with numbers and symbols', 'Don\'t click on suspicious links or pop-ups', 'Cyberbullying is wrong — always tell a teacher or parent if it happens'], 'tip': 'Think before you post! Anything you share online might stay there forever.', 'question': 'Should you share your login password with your friends?' }
};

Object.assign(data, ict);
fs.writeFileSync(path, JSON.stringify(data, null, 2));
console.log('ICT topics updated.');
